"""Roku table

Revision ID: f1760a4a0afe
Revises: a867befe4792
Create Date: 2022-08-13 17:58:34.901691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1760a4a0afe'
down_revision = 'a867befe4792'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roku',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip', sa.String(length=17), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('dev_type', sa.String(length=25), nullable=True),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_unique_constraint(None, 'room', ['url_path'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'room', type_='unique')
    op.drop_table('roku')
    # ### end Alembic commands ###
